const propiedades = [
  {
    titulo: "Casa en las afueras de la ciudad",
    descripcion: "6 ambientes, espaciosa, luminosa",
    tipo: "Casa",
    ciudad: "Resistencia",
    img: "img/casa2.jpg",
  },
  {
    titulo: "Departamento Zona Costanera",
    descripcion: "2 ambientes, balcón.",
    tipo: "Departamento",
    ciudad: "Corrientes",
    img: "img/depto1.jpg",
  },
  {
    titulo: "Local comercial en Microcentro",
    descripcion: "A una cuadra de la peatonal",
    tipo: "Local Comercial",
    ciudad: "Resistencia",
    img: "img/local1.jpg",
  },
  {
    titulo: "Departamento en Zona Centro",
    descripcion: "3 ambientes, espacioso, luminoso",
    tipo: "Departamento",
    ciudad: "Resistencia",
    img: "img/depto1.jpg",
  },
  {
    titulo: "Departamento Zona Costanera",
    descripcion: "1 ambiente, balcón.",
    tipo: "Departamento",
    ciudad: "Corrientes",
    img: "img/depto2.jpg",
  },
  {
    titulo: "Departamento",
    descripcion: "B° Belgrano",
    tipo: "Departamento",
    ciudad: "Resistencia",
    img: "img/depto4.jpg",
  },
  {
    titulo: "Casa en Barrio Privado",
    descripcion: "10 ambientes, ",
    tipo: "Casa",
    ciudad: "Corrientes",
    img: "img/casa3.jpg",
  },
  {
    titulo: "Departamento Zona Costanera",
    descripcion: "2 ambientes, balcón.",
    tipo: "Departamento",
    ciudad: "Corrientes",
    img: "img/depto4.jpg",
  },
  {
    titulo: "Local comercial",
    descripcion: "Zona céntrica",
    tipo: "Local Comercial",
    ciudad: "Resistencia",
    img: "img/local2.jpeg",
  },
];
